# Site settings
title: ".SANTA.REVISÃO."
description: "orientação e revisão de textos"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

plugins: 
  - jekyll-paginate

# Links
links:
  - title: "Sobre"
    url: /sobre
  - title: "Serviços"
    url: /servicos
  - title: "Trabalhos realizados"
    url: /trabalhos-realizados
  - title: "Depoimentos"
    url: /depoimentos
  - title: "Contato"
    url: /contato
