# Site settings
title: "Orientação & Revisão de Textos"
description: "..."
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 5

plugins: 
  - jekyll-paginate

# Links
links:
  - title: "Sobre"
    url: /sobre
  - title: "Serviços"
    url: /serviços
  - title: "Trabalhos realizados"
    url: /trabalhos-realizados
  - title: "Depoimentos"
    url: /depoimentos
  - title: "Contato"
    url: /contato
