# Site settings
title: "Revisão de Textos"
description: "..."
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 5

plugins: 
  - jekyll-paginate

# Links
links:
  - title: "Sobre"
    url: /sobre
  - title: "Pacotes"
    url: /pacotes
  - title: "Depoimentos"
    url: /depoimentos
  - title: "Contato"
    url: /contato
