# Site settings
title: "Revisao"
description: "So I was feeling nostalgic."
baseurl: ""
url: "http://alixedi.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 5

plugins: 
  - jekyll-paginate

# Links
links:
  - title: "abt"
    url: /about
  - title: "outra"
    url: /outra
